### ISSUE TITLE
Add some lib info

### ISSUE THREAD

**Issue by antoxa2584x** [universum-studios/android_fragments#9]
It is hard ti understand, what is this library about.
Add some info.

**Comment by albedinsky** [comment]
Hi, I added some library information as for separate modules into theirs corresponding **README.md** files and also there are some new pages in the **[Wiki](https://github.com/universum-studios/android_fragments/wiki)**. I would appreciate if you could check those and let me know your feedback.

**Comment by antoxa2584x** [comment]
@albedinsky That's better)
